protocomp: 
	g++ protocomp.cpp -o protocomp.exe

install:
	make
	mv -f protocomp.exe ../../designer/models/reactionnetworkmodel/protocomp.exe

update:
	../../designer/models/reactionnetworkmodel/protocomp ../../designer/models/reactionnetworkmodel/ReactionNetworkDataTypes.prototype
