protocomp: 
	g++ protocomp.cpp -o protocomp.exe

install:
	make
	mv -f protocomp.exe ../../src/designer/models/reactionnetworkmodel/protocomp.exe

update:
	../../src/designer/models/reactionnetworkmodel/protocomp ../../src/designer/models/reactionnetworkmodel/ReactionNetworkDataTypes.prototype
